/**
* This file was automatically generated by @oraichain/ts-codegen@0.35.9.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @oraichain/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import {Uint128, Binary, AssetInfo, Addr, Cw20ReceiveMsg, TransferBackMsg, Coin} from "./types";
import {InstantiateMsg, AllowMsg, ExecuteMsg, HookMethods, UpdatePairMsg, DeletePairMsg, RelayerFee, TokenFee, Ratio, QueryMsg, AdminResponse, AllowedResponse, Amount, ChannelResponse, Cw20CoinVerified, ChannelInfo, IbcEndpoint, ChannelWithKeyResponse, ConfigResponse, RelayerFeeResponse, ListAllowedResponse, AllowedInfo, ListChannelsResponse, PairQuery, MappingMetadata, ArrayOfPairQuery, PortResponse} from "./CwIcs20Latest.types";
export interface CwIcs20LatestReadOnlyInterface {
  contractAddress: string;
  port: () => Promise<PortResponse>;
  listChannels: () => Promise<ListChannelsResponse>;
  channel: ({
    id
  }: {
    id: string;
  }) => Promise<ChannelResponse>;
  channelWithKey: ({
    channelId,
    denom
  }: {
    channelId: string;
    denom: string;
  }) => Promise<ChannelWithKeyResponse>;
  config: () => Promise<ConfigResponse>;
  admin: () => Promise<AdminResponse>;
  allowed: ({
    contract
  }: {
    contract: string;
  }) => Promise<AllowedResponse>;
  listAllowed: ({
    limit,
    order,
    startAfter
  }: {
    limit?: number;
    order?: number;
    startAfter?: string;
  }) => Promise<ListAllowedResponse>;
  pairMappings: ({
    limit,
    order,
    startAfter
  }: {
    limit?: number;
    order?: number;
    startAfter?: string;
  }) => Promise<Addr>;
  pairMapping: ({
    key
  }: {
    key: string;
  }) => Promise<PairQuery>;
  pairMappingsFromAssetInfo: ({
    assetInfo
  }: {
    assetInfo: AssetInfo;
  }) => Promise<ArrayOfPairQuery>;
  getTransferTokenFee: ({
    remoteTokenDenom
  }: {
    remoteTokenDenom: string;
  }) => Promise<Ratio>;
}
export class CwIcs20LatestQueryClient implements CwIcs20LatestReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.port = this.port.bind(this);
    this.listChannels = this.listChannels.bind(this);
    this.channel = this.channel.bind(this);
    this.channelWithKey = this.channelWithKey.bind(this);
    this.config = this.config.bind(this);
    this.admin = this.admin.bind(this);
    this.allowed = this.allowed.bind(this);
    this.listAllowed = this.listAllowed.bind(this);
    this.pairMappings = this.pairMappings.bind(this);
    this.pairMapping = this.pairMapping.bind(this);
    this.pairMappingsFromAssetInfo = this.pairMappingsFromAssetInfo.bind(this);
    this.getTransferTokenFee = this.getTransferTokenFee.bind(this);
  }

  port = async (): Promise<PortResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      port: {}
    });
  };
  listChannels = async (): Promise<ListChannelsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_channels: {}
    });
  };
  channel = async ({
    id
  }: {
    id: string;
  }): Promise<ChannelResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      channel: {
        id
      }
    });
  };
  channelWithKey = async ({
    channelId,
    denom
  }: {
    channelId: string;
    denom: string;
  }): Promise<ChannelWithKeyResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      channel_with_key: {
        channel_id: channelId,
        denom
      }
    });
  };
  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  admin = async (): Promise<AdminResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      admin: {}
    });
  };
  allowed = async ({
    contract
  }: {
    contract: string;
  }): Promise<AllowedResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      allowed: {
        contract
      }
    });
  };
  listAllowed = async ({
    limit,
    order,
    startAfter
  }: {
    limit?: number;
    order?: number;
    startAfter?: string;
  }): Promise<ListAllowedResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_allowed: {
        limit,
        order,
        start_after: startAfter
      }
    });
  };
  pairMappings = async ({
    limit,
    order,
    startAfter
  }: {
    limit?: number;
    order?: number;
    startAfter?: string;
  }): Promise<Addr> => {
    return this.client.queryContractSmart(this.contractAddress, {
      pair_mappings: {
        limit,
        order,
        start_after: startAfter
      }
    });
  };
  pairMapping = async ({
    key
  }: {
    key: string;
  }): Promise<PairQuery> => {
    return this.client.queryContractSmart(this.contractAddress, {
      pair_mapping: {
        key
      }
    });
  };
  pairMappingsFromAssetInfo = async ({
    assetInfo
  }: {
    assetInfo: AssetInfo;
  }): Promise<ArrayOfPairQuery> => {
    return this.client.queryContractSmart(this.contractAddress, {
      pair_mappings_from_asset_info: {
        asset_info: assetInfo
      }
    });
  };
  getTransferTokenFee = async ({
    remoteTokenDenom
  }: {
    remoteTokenDenom: string;
  }): Promise<Ratio> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_transfer_token_fee: {
        remote_token_denom: remoteTokenDenom
      }
    });
  };
}
export interface CwIcs20LatestInterface extends CwIcs20LatestReadOnlyInterface {
  contractAddress: string;
  sender: string;
  receive: ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  transferToRemote: ({
    localChannelId,
    memo,
    remoteAddress,
    remoteDenom,
    timeout
  }: {
    localChannelId: string;
    memo?: string;
    remoteAddress: string;
    remoteDenom: string;
    timeout?: number;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateMappingPair: ({
    denom,
    isMintBurn,
    localAssetInfo,
    localAssetInfoDecimals,
    localChannelId,
    remoteDecimals
  }: {
    denom: string;
    isMintBurn?: boolean;
    localAssetInfo: AssetInfo;
    localAssetInfoDecimals: number;
    localChannelId: string;
    remoteDecimals: number;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  deleteMappingPair: ({
    denom,
    localChannelId
  }: {
    denom: string;
    localChannelId: string;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateConfig: ({
    admin,
    converterContract,
    defaultGasLimit,
    defaultTimeout,
    feeDenom,
    feeReceiver,
    relayerFee,
    relayerFeeReceiver,
    swapRouterContract,
    tokenFee
  }: {
    admin?: string;
    converterContract?: string;
    defaultGasLimit?: number;
    defaultTimeout?: number;
    feeDenom?: string;
    feeReceiver?: string;
    relayerFee?: RelayerFee[];
    relayerFeeReceiver?: string;
    swapRouterContract?: string;
    tokenFee?: TokenFee[];
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  increaseChannelBalanceIbcReceive: ({
    amount,
    destChannelId,
    ibcDenom,
    localReceiver
  }: {
    amount: Uint128;
    destChannelId: string;
    ibcDenom: string;
    localReceiver: string;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  reduceChannelBalanceIbcReceive: ({
    amount,
    ibcDenom,
    localReceiver,
    srcChannelId
  }: {
    amount: Uint128;
    ibcDenom: string;
    localReceiver: string;
    srcChannelId: string;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  overrideChannelBalance: ({
    channelId,
    ibcDenom,
    outstanding,
    totalSent
  }: {
    channelId: string;
    ibcDenom: string;
    outstanding: Uint128;
    totalSent?: Uint128;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  ibcHooksReceive: ({
    args,
    func,
    oraiReceiver
  }: {
    args: Binary;
    func: HookMethods;
    oraiReceiver: string;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class CwIcs20LatestClient extends CwIcs20LatestQueryClient implements CwIcs20LatestInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.receive = this.receive.bind(this);
    this.transferToRemote = this.transferToRemote.bind(this);
    this.updateMappingPair = this.updateMappingPair.bind(this);
    this.deleteMappingPair = this.deleteMappingPair.bind(this);
    this.updateConfig = this.updateConfig.bind(this);
    this.increaseChannelBalanceIbcReceive = this.increaseChannelBalanceIbcReceive.bind(this);
    this.reduceChannelBalanceIbcReceive = this.reduceChannelBalanceIbcReceive.bind(this);
    this.overrideChannelBalance = this.overrideChannelBalance.bind(this);
    this.ibcHooksReceive = this.ibcHooksReceive.bind(this);
  }

  receive = async ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      receive: {
        amount,
        msg,
        sender
      }
    }, _fee, _memo, _funds);
  };
  transferToRemote = async ({
    localChannelId,
    memo,
    remoteAddress,
    remoteDenom,
    timeout
  }: {
    localChannelId: string;
    memo?: string;
    remoteAddress: string;
    remoteDenom: string;
    timeout?: number;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      transfer_to_remote: {
        local_channel_id: localChannelId,
        memo,
        remote_address: remoteAddress,
        remote_denom: remoteDenom,
        timeout
      }
    }, _fee, _memo, _funds);
  };
  updateMappingPair = async ({
    denom,
    isMintBurn,
    localAssetInfo,
    localAssetInfoDecimals,
    localChannelId,
    remoteDecimals
  }: {
    denom: string;
    isMintBurn?: boolean;
    localAssetInfo: AssetInfo;
    localAssetInfoDecimals: number;
    localChannelId: string;
    remoteDecimals: number;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_mapping_pair: {
        denom,
        is_mint_burn: isMintBurn,
        local_asset_info: localAssetInfo,
        local_asset_info_decimals: localAssetInfoDecimals,
        local_channel_id: localChannelId,
        remote_decimals: remoteDecimals
      }
    }, _fee, _memo, _funds);
  };
  deleteMappingPair = async ({
    denom,
    localChannelId
  }: {
    denom: string;
    localChannelId: string;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      delete_mapping_pair: {
        denom,
        local_channel_id: localChannelId
      }
    }, _fee, _memo, _funds);
  };
  updateConfig = async ({
    admin,
    converterContract,
    defaultGasLimit,
    defaultTimeout,
    feeDenom,
    feeReceiver,
    relayerFee,
    relayerFeeReceiver,
    swapRouterContract,
    tokenFee
  }: {
    admin?: string;
    converterContract?: string;
    defaultGasLimit?: number;
    defaultTimeout?: number;
    feeDenom?: string;
    feeReceiver?: string;
    relayerFee?: RelayerFee[];
    relayerFeeReceiver?: string;
    swapRouterContract?: string;
    tokenFee?: TokenFee[];
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_config: {
        admin,
        converter_contract: converterContract,
        default_gas_limit: defaultGasLimit,
        default_timeout: defaultTimeout,
        fee_denom: feeDenom,
        fee_receiver: feeReceiver,
        relayer_fee: relayerFee,
        relayer_fee_receiver: relayerFeeReceiver,
        swap_router_contract: swapRouterContract,
        token_fee: tokenFee
      }
    }, _fee, _memo, _funds);
  };
  increaseChannelBalanceIbcReceive = async ({
    amount,
    destChannelId,
    ibcDenom,
    localReceiver
  }: {
    amount: Uint128;
    destChannelId: string;
    ibcDenom: string;
    localReceiver: string;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      increase_channel_balance_ibc_receive: {
        amount,
        dest_channel_id: destChannelId,
        ibc_denom: ibcDenom,
        local_receiver: localReceiver
      }
    }, _fee, _memo, _funds);
  };
  reduceChannelBalanceIbcReceive = async ({
    amount,
    ibcDenom,
    localReceiver,
    srcChannelId
  }: {
    amount: Uint128;
    ibcDenom: string;
    localReceiver: string;
    srcChannelId: string;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      reduce_channel_balance_ibc_receive: {
        amount,
        ibc_denom: ibcDenom,
        local_receiver: localReceiver,
        src_channel_id: srcChannelId
      }
    }, _fee, _memo, _funds);
  };
  overrideChannelBalance = async ({
    channelId,
    ibcDenom,
    outstanding,
    totalSent
  }: {
    channelId: string;
    ibcDenom: string;
    outstanding: Uint128;
    totalSent?: Uint128;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      override_channel_balance: {
        channel_id: channelId,
        ibc_denom: ibcDenom,
        outstanding,
        total_sent: totalSent
      }
    }, _fee, _memo, _funds);
  };
  ibcHooksReceive = async ({
    args,
    func,
    oraiReceiver
  }: {
    args: Binary;
    func: HookMethods;
    oraiReceiver: string;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      ibc_hooks_receive: {
        args,
        func,
        orai_receiver: oraiReceiver
      }
    }, _fee, _memo, _funds);
  };
}