/**
* This file was automatically generated by @oraichain/ts-codegen@0.35.9.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @oraichain/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import {Uint128, Binary, SwapOperation, AssetInfo, Addr, Percentage, Cw20ReceiveMsg, PoolKey, FeeTier} from "./types";
import {InstantiateMsg, ExecuteMsg, QueryMsg, ConfigResponse, SimulateSwapOperationsResponse} from "./Oraidex.types";
export interface OraidexReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<ConfigResponse>;
  simulateSwapOperations: ({
    offerAmount,
    operations
  }: {
    offerAmount: Uint128;
    operations: SwapOperation[];
  }) => Promise<SimulateSwapOperationsResponse>;
}
export class OraidexQueryClient implements OraidexReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.simulateSwapOperations = this.simulateSwapOperations.bind(this);
  }

  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  simulateSwapOperations = async ({
    offerAmount,
    operations
  }: {
    offerAmount: Uint128;
    operations: SwapOperation[];
  }): Promise<SimulateSwapOperationsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      simulate_swap_operations: {
        offer_amount: offerAmount,
        operations
      }
    });
  };
}
export interface OraidexInterface extends OraidexReadOnlyInterface {
  contractAddress: string;
  sender: string;
  receive: ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  executeSwapOperations: ({
    minimumReceive,
    operations,
    to
  }: {
    minimumReceive?: Uint128;
    operations: SwapOperation[];
    to?: Addr;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  executeSwapOperation: ({
    operation,
    sender,
    to
  }: {
    operation: SwapOperation;
    sender: Addr;
    to?: Addr;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  assertMinimumReceiveAndTransfer: ({
    assetInfo,
    minimumReceive,
    receiver
  }: {
    assetInfo: AssetInfo;
    minimumReceive: Uint128;
    receiver: Addr;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateConfig: ({
    factoryAddr,
    factoryAddrV2,
    oraiswapV3,
    owner
  }: {
    factoryAddr?: string;
    factoryAddrV2?: string;
    oraiswapV3?: string;
    owner?: string;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class OraidexClient extends OraidexQueryClient implements OraidexInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.receive = this.receive.bind(this);
    this.executeSwapOperations = this.executeSwapOperations.bind(this);
    this.executeSwapOperation = this.executeSwapOperation.bind(this);
    this.assertMinimumReceiveAndTransfer = this.assertMinimumReceiveAndTransfer.bind(this);
    this.updateConfig = this.updateConfig.bind(this);
  }

  receive = async ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      receive: {
        amount,
        msg,
        sender
      }
    }, _fee, _memo, _funds);
  };
  executeSwapOperations = async ({
    minimumReceive,
    operations,
    to
  }: {
    minimumReceive?: Uint128;
    operations: SwapOperation[];
    to?: Addr;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      execute_swap_operations: {
        minimum_receive: minimumReceive,
        operations,
        to
      }
    }, _fee, _memo, _funds);
  };
  executeSwapOperation = async ({
    operation,
    sender,
    to
  }: {
    operation: SwapOperation;
    sender: Addr;
    to?: Addr;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      execute_swap_operation: {
        operation,
        sender,
        to
      }
    }, _fee, _memo, _funds);
  };
  assertMinimumReceiveAndTransfer = async ({
    assetInfo,
    minimumReceive,
    receiver
  }: {
    assetInfo: AssetInfo;
    minimumReceive: Uint128;
    receiver: Addr;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      assert_minimum_receive_and_transfer: {
        asset_info: assetInfo,
        minimum_receive: minimumReceive,
        receiver
      }
    }, _fee, _memo, _funds);
  };
  updateConfig = async ({
    factoryAddr,
    factoryAddrV2,
    oraiswapV3,
    owner
  }: {
    factoryAddr?: string;
    factoryAddrV2?: string;
    oraiswapV3?: string;
    owner?: string;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_config: {
        factory_addr: factoryAddr,
        factory_addr_v2: factoryAddrV2,
        oraiswap_v3: oraiswapV3,
        owner
      }
    }, _fee, _memo, _funds);
  };
}