[workspace]
members = ["contracts/*", "packages/*"]

resolver = "2"

[workspace.dependencies]
cosmwasm-testing-util = { git = "https://github.com/oraichain/cosmwasm-testing-util.git", rev = "24c138c" }
oraiswap = { git = "https://github.com/oraichain/oraiswap.git", rev = "03f4955b" }
# osmosis-test-tube = { git = "https://github.com/oraichain/test-tube.git", rev = "354d580" }

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
