[[chains]]
id = 'Earth'
rpc_addr = 'http://earth:26657'
grpc_addr = 'http://earth:9090'
websocket_addr = 'ws://earth:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'earth'
key_name = 'testkey'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.000, denom = 'earth' }
gas_multiplier = 1.1
clock_drift = '5s'
trusting_period = '6000s'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'Mars'
rpc_addr = 'http://mars:26657'
grpc_addr = 'http://mars:9090'
websocket_addr = 'ws://mars:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'mars'
key_name = 'testkey'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.000, denom = 'mars' }
gas_multiplier = 1.1
clock_drift = '5s'
trusting_period = '6000s'
trust_threshold = { numerator = '1', denominator = '3' }