[package]
name = "cw20-ics20-msg"
version = "0.0.3"
authors = ["Oraichain Labs"]
edition = "2021"
description = "Definition and types for the cw20-ics20-msg interface"
license = "MIT"
repository = "https://github.com/Oraichain/ibc-bridge-wasm"
homepage = "https://orai.io"
documentation = "https://docs.orai.io"
readme = "README.md"

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
cw20 = { workspace = true }
oraiswap = { workspace = true }
bech32 = "0.8.1"
anybuf = "0.3.0"
prost = { workspace = true }

[dev-dependencies]
cosmwasm-testing-util = { workspace = true }
cosmwasm-vm = { workspace = true }
