[package]
name = "cw20-ics20-msg"
version = "0.0.3"
authors = ["Oraichain Labs"]
edition = "2021"
description = "Definition and types for the cw20-ics20-msg interface"
license = "MIT"
repository = "https://github.com/Oraichain/ibc-bridge-wasm"
homepage = "https://orai.io"
documentation = "https://docs.orai.io"
readme = "README.md"

[dependencies]
cosmwasm-schema = "=1.2"
cosmwasm-std = { version = "=1.2", default-features = false }
cw-storage-plus = "1.0.1"
cw20 = "1.0.1"
schemars = "0.8.1"
bech32 = "0.8.1"
oraiswap = { git = "https://github.com/oraichain/oraiswap.git", rev = "03f4955b" }
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
anybuf = "0.3.0"

[dev-dependencies]
cw-multi-test = "0.16.0"
cosmwasm-testing-util = { git = "https://github.com/oraichain/cosmwasm-testing-util.git", rev = "70c4b6c" }
cosmwasm-vm = { version = "=1.2" }
